spring:
  config:
    import: optional:file:.env
  application:
    name: shop
  datasource:
    # Postgres 서버 타임존을 서울(KST)로 맞추기 위해 옵션 추가
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jackson:
    time-zone: ${SPRING_JACKSON_TIME_ZONE}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_HIBERNATE_FORMAT_SQL}
        jdbc:
          time_zone: ${SPRING_JPA_HIBERNATE_JDBC_TIME_ZONE}

api:
  v1: /api/v1

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY}
    success-url: ${TOSS_SUCCESS_URL}
    fail-url: ${TOSS_FAIL_URL}